### ISSUE TITLE
Style guides and linter configuration

### ISSUE THREAD

**Issue by lgruen** [populationgenomics/team-docs#3]
We should have a section in the docs that has a link to style guides and our linter configurations. I'd suggest focussing on Python first.

It's probably a good idea to adopt an existing style guide. Maybe we can take the one from Hail as a baseline, since we'll work on that project anyway?

**Comment by vladsaveliev** [comment]
Hail is using [pylint](http://pylint.pycqa.org/en/latest/), which looks like a good option. I [started with a simpler repository](https://github.com/populationgenomics/interview-exercises/compare/lint?expand=1) and added pylint as part of the CI. 

Next steps:
- Make sure `.pylintrc` is respected by IDEs like VScode and PyCharm and document in the team docs if it's not trivial.
- Add more tools like flake8 and/or mypy. From https://www.reddit.com/r/Python/comments/82hgzm/any_advantages_of_flake8_over_pylint/:
> Flake8 supports plugins for many things that Pylint can't do at all - from docstring style, to type checking (driving Mypy), to checking for graphically similar unicode characters flake8-confusables. It's also easy to write your own plugins, to drive custom static checks or anything else that reads code

- Consider automating style fixing with tools like [prettier](https://prettier.io/) or [black](https://github.com/psf/black) (I checked black and it seems to be too restrictive and non-customizable).
- Run through other repositories in the org.
- Consider customizing the code style (e.g. get the max line width wider)?

Also FYI Hail pylint configuration: https://github.com/hail-is/hail/blob/main/pylintrc

**Comment by lgruen** [comment]
Sounds great!

> Make sure .pylintrc is respected by IDEs like VScode and PyCharm and document in the team docs if it's not trivial.

Visual Studio Code auto-detects `.pylintrc` and asks the user whether to install `pylint` (or another linter like `flake8`) if it's not installed already.

**Comment by lgruen** [comment]
The new configs are amazing! :)

Regarding `pylint-quotes`: according to the [documentation](https://github.com/edaniszewski/pylint-quotes), it needs to be loaded as a plug-in to `pylint`: `pylint --load-plugins pylint_quotes <module-or-package>`. I can't see that in the current description / workflows in [the documentation](https://github.com/populationgenomics/team-docs/blob/main/python_code_style.md). Is that an omission or is it enabled another way?

As we use conda for most of our dependency management, should we also use that in the workflow / example instructions? There's a [setup-miniconda](https://github.com/marketplace/actions/setup-miniconda) action that's pretty handy. However, I couldn't find the `pylint-quotes` package in conda -- maybe we'd need to port that?

**Comment by vladsaveliev** [comment]
Re `pylint-quotes`: the plug in is loaded in the `.pylint` config. All pylint options are duplicated in the config. Same goes for other linters too.

Yeah, it's missing from conda, so I replaced `pylint-quotes` with `flake8-quotes` which is on conda; though ultimately it didn't matter as we rely on `pre-commit` to install tools from GitHub anyway.

**Comment by vladsaveliev** [comment]
All done for now and documented in https://github.com/populationgenomics/team-docs/blob/main/python_code_style.md

Happy to adjust in the future - it'll very likely be needed as we will keep finding some inspections unreasonable for particular cases.
